apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: bazarr
  name: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bazarr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: bazarr
    spec:
      containers:
        - env:
            - name: PGID
              value: "1002"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Europe/Paris
          image: linuxserver/bazarr:latest
          name: bazarr
          ports:
            - containerPort: 6767
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: bazarr-claim0
            - mountPath: /movies
              name: bazarr-claim1
            - mountPath: /tv
              name: bazarr-claim2
      restartPolicy: Always
      volumes:
        - name: bazarr-claim0
          persistentVolumeClaim:
            claimName: bazarr-claim0
        - name: bazarr-claim1
          persistentVolumeClaim:
            claimName: bazarr-claim1
        - name: bazarr-claim2
          persistentVolumeClaim:
            claimName: bazarr-claim2
status: {}
