version: "3"
# media containers
services:

  ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    restart: always
    ports:
      - 3579:3579
    environment:
      - "Logging:LogLevel:Default=Warning"
      - "Logging:LogLevel:System=Warning"
      - PUID=1001
      - PGID=1002
      - TZ=Europe/Paris
    volumes:
      - /mnt/gloubinours/jellies-db/ombi/config:/config
      - /etc/localtime:/etc/localtime:ro
      - "${PWD}/ombi/appsettings.json:/opt/ombi/appsettings.json"
  sonarr:
    image: linuxserver/sonarr:latest
    restart: always
    #    user: 1001:1002
    environment:
      - PUID=1020
      - PGID=1002
      - TZ=Europe/Paris
    volumes:
      - /mnt/gloubinours/jellies-db/sonarr/config:/config
      - /mnt/gloubinours/shows:/tv
      - /mnt/gloubinours/transmission:/downloads
    ports:
      - 8989:8989

  radarr:
    image: "linuxserver/radarr:nightly"
    container_name: radarr
    restart: always
    environment:
      - "PUID=1000"
      - "PGID=1002"
      - TZ=Europe/Paris
    volumes:
      - /mnt/gloubinours/jellies-db/radarr/config:/config
      - /mnt/gloubinours/movies:/movies
      - /mnt/gloubinours/transmission:/downloads
    ports:
      - "7878:7878"

  bazarr:
    image: linuxserver/bazarr:latest
    restart: always
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=Europe/Paris
    volumes:
      - /mnt/gloubinours/jellies-db/bazarr/config:/config
      - /mnt/gloubinours/movies:/movies
      - /mnt/gloubinours/shows:/tv
    ports:
      - 6767:6767
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
    #   - "traefik.http.routers.bazarr.rule=Host(`bazarr.doxx.fr`)"
    #   - "traefik.http.routers.bazarr.middlewares=private@file"

  lidarr:
    image: linuxserver/lidarr:latest
    restart: always
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=Europe/Paris
    ports: 
      - 8686:8686
    volumes:
      - /mnt/gloubinours/jellies-db/lidarr/config:/config
      - /mnt/gloubinours/music:/music
      - /mnt/gloubinours/transmission:/downloads
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.services.lidarr.loadbalancer.server.port=8686"
    #   - "traefik.http.routers.lidarr.rule=Host(`lidarr.doxx.fr`)"
    #   - "traefik.http.routers.lidarr.middlewares=private@file"

        #
        #readarr:
        #    image: linuxserver/readarr:nightly
        #    restart: always
        #    environment:
        #      - PUID=33
        #      - PGID=33
        #      - TZ=America/New_York
        #    volumes:
        #      - /tank/container_data/readarr:/config
        #      - /tank/cloud/books:/books
        #      - /tank/downloads:/downloads
        #    expose:
        #      - 8787
        #    # depends_on:
        #    #   - qbittorrent
        #    #   - nzbget
        #    #   - prowlarr
        #    labels:
        #      - "traefik.enable=true"
        #      - "traefik.http.services.readarr.loadbalancer.server.port=8787"
        #      - "traefik.http.routers.readarr.rule=Host(`readarr.doxx.fr`)"
        #      - "traefik.http.routers.readarr.middlewares=private@file"
        #

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    ports:
      - "9117:9117"
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Paris
    volumes:
      - /mnt/gloubinours/jellies-db/jackett/config:/config
      - /etc/localtime:/etc/localtime:ro


    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.jackett.entrypoints=web,websecure"
    #   - "traefik.http.routers.jackett.rule=Host(`jackett.doxx.fr`)"
    #   - "traefik.http.services.jackett.loadbalancer.server.port=9117"
    #   - "traefik.http.routers.jackett.tls=true"
    #   - "traefik.http.routers.jackett.tls.certresolver=leresolver"
# jellyfin:
#   image: jellyfin/jellyfin:latest
#   restart: always
#   environment:
#     - UID=33
#     - GID=33
#     - TZ=America/New_York
#   devices:
#     - /dev/dri
#   volumes:
#     - /tmp/jellyfin:/transcodes
#     - /tank/container_data/jellyfin_config:/config
#     - /tank/container_data/jellyfin_cache:/cache
#     - /tank/cloud/videos:/media/video:ro
#     - /tank/cloud/music:/media/music:ro
#     - /tank/cloud/books:/media/books:ro
#   expose:
#     - 8096
#   ports:
#     - 1900:1900/udp
#   labels:
#     - "traefik.enable=true"
#     - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
#     - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.doxx.fr`)"
#     - "traefik.http.routers.jellyfin.middlewares=secure@file"

#qbittorrent:
#   image: linuxserver/qbittorrent:latest
#   restart: always
#   environment:
#     - PUID=33
#     - PGID=33
#     - UMASK=022
#     - TZ=America/New_York
#     - WEBUI_PORT=8080
#   volumes:
#     - /tank/container_data/qbittorrent:/config
#     - /tank/downloads:/downloads
#   expose:
#     - 8080
#   ports:
#     - 1080:1080/tcp
#     - 1080:1080/udp
#   labels:
#     - "traefik.enable=true"
#     - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
#     - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.doxx.fr`)"
#     - "traefik.http.routers.qbittorrent.middlewares=private@file"

  # nzbget:
  #   image: linuxserver/nzbget:latest
  #   restart: always
  #   environment:
  #     - PUID=33
  #     - PGID=33
  #     - UMASK=022
  #     - TZ=America/New_York
  #   volumes:
  #     - /tank/container_data/nzbget:/config
  #     - /tank/downloads/nzbget:/downloads
  #   expose:
  #     - 6789
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.services.nzbget.loadbalancer.server.port=6789"
  #     - "traefik.http.routers.nzbget.rule=Host(`nzbget.doxx.fr`)"
  #     - "traefik.http.routers.nzbget.middlewares=private@file"

  # prowlarr:
  #   image: linuxserver/prowlarr:nightly
  #   restart: always
  #   environment:
  #     - PUID=33
  #     - PGID=33
  #     - TZ=America/New_York
  #   volumes:
  #     - /tank/container_data/prowlarr:/config
  #   expose:
  #     - 9696 
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
  #     - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.doxx.fr`)"
  #     - "traefik.http.routers.prowlarr.middlewares=private@file"
